os: osx
language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@latest
install:
- npm install --silent
script:
- npm start
notifications:
  email: false
